kind: ConfigMap
apiVersion: v1
metadata:
  name: sting-as-data
  namespace: default
data:
  index.html: |
    <html>
      <body style="font-family:monospace">
        AS216455 is an educational network. It also provides IPv6 tunnels for residential users that do not receive IPv6 from their ISP.
        <br />
        Open for peering. Contact <a href="mailto:noc@as216455.net">noc@as216455.net</a> for more information.
        <br />
        <p>Contact: <a href="mailto:noc@as216455.net">noc@as216455.net</a> | Abuse: <a href="mailto:abuse@as216455.net">abuse@as216455.net</a> | <a href="https://www.peeringdb.com/net/33889">PeeringDB</a> | <a href="https://bgp.tools/as/216455">bgp.tools</a> | <a href="https://as216455.net/geofeed.csv">geofeed.csv</a></p>
      </body>
    </html>
  geofeed.csv: |
    2a05:dfc1:8500::/40,NL,NL-NH,Amsterdam,
    2a05:dfc1:9600::/40,NL,NL-NH,Amsterdam,
    2a05:dfc1:8501::/48,NL,NL-NH,Amsterdam,
    2a05:dfc1:8502::/48,NL,NL-NH,Amsterdam,
    2a05:dfc1:8510::/48,NL,NL-NH,Amsterdam,
    2a05:dfc1:858f::/48,NL,NL-NB,Eindhoven,
    2a07:54c7:5000::/36,NL,NL-NH,Amsterdam
    2a07:54c7:5100::/40,NL,NL-NH,Amsterdam
    2a07:54c7:5100:abba::/64,NL,NL-NH,Amsterdam
    2a07:54c7:5901::/48,NL,NL-NH,Amsterdam
  pgp-key.asc: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Comment: 91DC 1E29 E8FE CD76 4789  2979 3CEC 44B4 942D A526
    Comment: Sting Alleman <me@stingalleman.nl>

    mQINBGh2L2sBEACqftlgm56svszN+uzWJPyTPNRQJQcBWtvP2dJHEopDYagALjZT
    yCapKt8Capjqk6qFHYMb1Bco0tNCdpg3qXNUzTSP+ecOo2myn/vFYe+s+WLF2lNm
    XpzhzuuVsxF/vCapIOh2AlAO3SE3vknkV6OYYbxpp+R+vRBHJUcY5GJgLX2DicTG
    eHxr04UzCveLl4t2Ef5ss1jHOvVm7n75eqmVaabIqI66nS7q05qAdcI/zwJT4EGd
    S6qkPlCoIEQ4tIxMoMMW6rJ+HmkQQ1SESgwDfcFu/Z8BppzkyxqvvU5shyOYPky6
    jOM99pKQQtnYoffh1Cg4zM+qaHXK0OiNyRmbf0LorDRFBDcqmfcJlYEQZOJxMLYy
    LtFKfWgtaGfc5cI1984xvp1qCoRe5pAAB7S3AlcKqSMHI/UGrOhw5QyY3aE/5Dp7
    GHf9WStTrsgBMQRQ1qI+xrsekc8h9Ou2pV3D56e96TrVqHgs6oLBL7ZTiy24EpYn
    GfKd/r98sEsbUU3yTihPZ8mWKzI032bRrMz1pUBKeffletU1GNVNejeom8gsFr4q
    NWdO0BIyIkyI6W4J46mGu/aUImN26ERv8qz8ZoF7dKGF8CElJIO2LBVMb7JJWS5S
    LL6Fw63DJzi2dGKB967Y24o9HIFBUmLVhx7r5ihse7xWnXDF12lVvu93lQARAQAB
    tCJTdGluZyBBbGxlbWFuIDxtZUBzdGluZ2FsbGVtYW4ubmw+iQJRBBMBCAA7FiEE
    kdweKej+zXZHiSl5POxEtJQtpSYFAmh2L2sCGwEFCwkIBwICIgIGFQoJCAsCBBYC
    AwECHgcCF4AACgkQPOxEtJQtpSYcFw//S+7ZJvDo23UfcmyYoZmzxuRBldetw/qe
    q+BoFZFpJvik7Dr0Mkdj9iMAJl6P9AkNWWMbcXhJY+TypCNklaD98QRyEP4wci9c
    evWj/f82tHTOLA24n4cgzKbekDK52x9Fmu1uh4BtxpHAADCkJLcWOstdQVxxdihz
    777je02YwbtYklgN5X6W1cpNZHqU6c4RqvcEbr5vMswBws9WgyGxouj5uO1dQo6r
    k7oSGxFy2eXj1zfrJimsCig8yBgXNmHBpxXVcsYwSrYshYTBvDPOldW8O955CGgO
    iq83tqGGORZWqtBiuhPym6+qe4CTgguCfV3e54eGJ/kQO2eAW6pm7qZvytc1c8HD
    FtHvpopflalNkiqPkCGuTSuQAyKcXVhxX/m2EG2k7drCZQBYrgXmnj70UZ8gAj91
    356hTyYTbDfdKKB+kBLeJT0zZ2AxhKjMwCRSewuS4tX+CFRQgl6C8QdE21mN7ghK
    /6vrh2wltHf/n77wvzzCwMsqVnQ6yqfysql4x63zyMRXskcoVMDwj/HLS1ce0BKi
    a6Py2nop30jTA3r5yhci9nD6vpil5ZIeIrhN6e6SFEtNHqVNeexV7KxvAuU/ySSv
    eg1ECBM190L+te0H00qnbbUKlPwq2HjvXYDSxt5NQ7Okyhj5GGiL8j5w+erpQVac
    mtCKklSnrpy5Ag0EaHYvhQEQANHbSniCRrMqYNAQ3fjoeXBsrO+f0cZO0kxClqjD
    t8wTB2YuebW5XyA74/zO/JWwr9qBcLy1KGV4gIwIHKb0vpciujmqgy7ZMoQ8CFFz
    inAV4xeAw0jX2Mgw2Fl/k93tt/Lh5ABeeS5b1O2vC1jfmpPNhtYIyQ7gcrDWl3JF
    Gg/L9vhPBdEqyDhnTIm2J0w+igY64mxhuWil9KlVrUJ5YBUOfln4enMhpnn96BJX
    tRUBmLkmQd342yks5SwFEQwXxgouTQYflQB4enryBVcuS9XH2bK016g74y0M9Nuj
    ySjRI0XhcQt2LUX93nijpqhXUVkByx3aa+MvYVBh9+AtjRq3PWeCvQOxt5Fk4CWY
    4wpdbqeCYuZq/BOweCpW6m+NNenfCLaw0Y1kI7nHEwdM1rlr//Io1EtUwqG4XjHA
    SLYSxfOBfUOrCQAhdbe7l0jqOkxsQ8GB5j3szw7kb5QzozM80qGatMMPt/C9e7T/
    5gpyRxzBUQjotvZqsHuGocQGvY50IT2PRfy9pEl7ldXP//tawioRmXSbIyMx76tm
    L7YHv79W/GeWpcVwHGR0a+YxcPU9Gckz1kcGxCveULgNz8V0KCs5xLrTBWD0bB7v
    4MYw0x6naZVybv+/yZRT/STLoGn6iI2EkvWtCs/9aXfNAHgFIkCkb7qKSZrQtjxd
    13NHABEBAAGJBHIEGAEIACYWIQSR3B4p6P7NdkeJKXk87ES0lC2lJgUCaHYvhQIb
    AgUJAeEzgAJACRA87ES0lC2lJsF0IAQZAQgAHRYhBH1nZOYhxdb6w+BmgkChX3sj
    fgGeBQJodi+FAAoJEEChX3sjfgGeyucP/2PHhkNVmGA27BKTHBWUNgKDrFnjGPaU
    tCV7/xdlm9uldRcc+qNq20rE8x7YhYu0ChMmrvcJx4SvOBxxsIgPEq4BhwljJfrl
    qo0IrSEcfkjJQ1QqIkGgou+ZVIzr24BH6TdtXUZKLijYfR9R7MSqNv1y+gixH4Rm
    MbmoH++3U9WxmRphabyuVVfen1zLKwIEKJkNjDx0yKN1HumdEH3QKjcPDQXp/3Fh
    8EnOirZzbHBD9s52E46Fafd2ra+bL5KGl1Xqp3PcdkHuiT6Ujxdcx8VV4OasQw6V
    godBoXEoG3KnAd0DG5xEC2mf08xwY6koJQCThMThNxcNQhHXAgBaSGceDCAnGXwp
    F1Kn4Kr2bon1G1DDnhKArvcjqXbBK785trtO1GCcusw85EKXq3ZKeYBAODCqNge/
    8EqtLWOYm2DDMrt8gcbryiAYi3brwTNiCFb8/YPpIZU3/+zMfeCDtuipQp4hbizZ
    98rpgrvlFj2R9Ih4vDQJxrvd9sL8cT0SDQIdk0Rgc0Q3ztnDLRlV20bzNHt/xgd4
    SpoaFs74RY4LoTt+qH5SZSDMnrkbJziu1PY0nlJw9H5sRy0KWsb60JLkp/WKZlLy
    91RCs/AiLxEtOwEToonbUasYdCbZEeH4xh8wSqaQFouCMU9H/UId81jIPb2v2qfJ
    udCO7F4zGEu9I5EP/R3dJY0n1tGSW/6dExOvyjDqeaz2lPIN2873u47j0uLmMt3k
    3LqKKWGKvNYEcOkgTckjc1Eze98y7tE2SRuw7hrQ56x7p293JoiEIGFht6R+rkvz
    BVcF7t3cMvyuEeCHln2/hgQb68usgTCl/2AajKSdmAo9KF6Ybl0uR7kWYg8lOYwU
    XWwys0+w8l8iOwnij5idN5K7GPWstWkAHcSEHN0J1DHYiu6f21q5aE6btKm1yTYI
    C4FBhkFqJpfPvkyZhiw031sx+wJ3blSsgYF7D/ieDmbV4dkz6Ka1nqPhpt2laR/5
    MJUxvUtfpyI1QVzt18nGPt0QXPpNO7PEV0N3exZtNW5fCayKQznQmsopVfNrunN8
    Sq3P6QTuyABdAhjhFSeFuLaE03QikDE+mA7F1CCef8AQMSoYTvp/RNfKCKalspSN
    eVXixw80JGRYBtacaP8GFAHazu462XSiMmtDlxSERMZO32ln5Qo2O/AtsaFQtG/H
    lUQzZRGyQi8Lf4x1fneCDxCEmOIybCsk/4IhHbiDiN/ARcrGLSOgVi+D9ulihbvU
    g0es9AK+FrEvNCJLU0GugufIN5Sdwpb3UEVuixofgbYuN2N784sYGsofzf6mRdlu
    fZCcxiFP0A23BlnTRnBrM9epgOsTl/G0Fd0g+j2UFCyVp1TuyDWo1tMglMyzuQIN
    BGh2L4YBEAC59dJxXQtXDi4Gy3rr6o5U0roiS3zl4gXnXODciC1VeuKKYTBuCQTQ
    SE5qlKaiyAVHZ9VzsUZS+7OJnBs7smqILHNElDjdrvjAq+HYzTJexCDpnGOzKfHr
    gZofiJaLFwO2c8SQCUwohmMV9V94C6S9LgEoQhcK10gJIK8r7v3OS1ck6LljRBdy
    ngon4j8RDV8t4Mhnt7XcMQ7dZLrVcdrR3R6LnT5xZeCYD30dPVqHBtt+b8NP+Maq
    LNa6KFqpwC4ZEU3Ho6TeIefYOBcXdRTXWXEZMZMWaF0SzOUbw+0tig2Mn8IF8EWK
    SgWDVDez6jDaCIm4jMfjHAA1M8B01YDgfcpIr7WdLUAe7lS8PoNSSlGgycMkpdrT
    vlmN+TlT/GBIBj2VLRYamdLjnGAovLpoUETslwF9gJQlbsrI80skpx9n6qrCVXLn
    eygIixH/1vzsjeifLbzGtjWcaad/UYC6Gyt1vTrcJwC9a3WXmIhudvjONt8mc9SR
    8kGs20ORgpzWeMZfB9FfB7koK7UIQzUlhl2cSgNH0zpn7GifB96TX2j0in3PCrEB
    18lQXSZUq5KVzyYeonOohrSDTd7GD9LDv+pemPUGGPgISzIZw5K7g/vqijoQxgu1
    74d9GEl53CImtgU9W5r4oeQKdthpWokx5i5sg8wti1xdgQ3FiX2qKwARAQABiQI8
    BBgBCAAmFiEEkdweKej+zXZHiSl5POxEtJQtpSYFAmh2L4YCGwwFCQHhM4AACgkQ
    POxEtJQtpSZGlw//WvZbogcB+PiSCqdIJ0dRUCcttbWwLeBou0BcG5gzF9vGnY2g
    Y2xv/Nj4ueBk3CI4JBbh4JeJBBBsrl+bVYom/uIJt7nZNUNhNao6QVj5tGoRCu2n
    Ji6nCX3i2zfiw7VtxQRggrv9up6+8sOIHVk4PfXllwnuS6g2MFI30F6iIDWX12eN
    4sHfdkIq/axAUm9tTU4sfTy7mTjZCTpTRWNPgWvjNJbg16bZrsuWE2gM0BJ/oOIr
    7khSInN2zqqAQSGO8dSkib6+n391kIB/gwNYmP7uTPBcdXodJ/IQHJ3qzZ3Ny8BX
    H46PGov7Ey9/p5zJKEUIDbs7EMaILsX+kxE4IGYz9fvXJlqxvCb6YZDsgG+FImVS
    XIVx3pfju/NU+Ug7FGbHdawKIY56hHLVrTJ6iU3LscY2paZohoNfbMIywHHxcTep
    +0XIsmSP2rV0dH9vlJhOG72dOWTexFjkV9KncJGElrKRDNMqn5BGy9vjdVUvQMQF
    ZMqwRfpRh1wZgGtGqrhOLt3caCh8c68v2OVTZE3gfrLwe/OHdZ7WOfX+kcLH2lAk
    ClgtAWdcQ7N89tPPaEeQLCWhoufsGU18EXX03JfCTJceSfTIm/gH6MV1R/oOpNA7
    QIyk5t6LyWWi6qL4mQpC4rzkHmZsJTVByuTf7yo2pBwzqpFvu7XEkqqYNMe4MwRo
    di+UFgkrBgEEAdpHDwEBB0Az9jPLOVJzUHkJEDfwN/YyndBeKM1QjbzCGzNj+hYZ
    gYkCPAQYAQgAJhYhBJHcHino/s12R4kpeTzsRLSULaUmBQJodi+UAhsgBQkB4TOA
    AAoJEDzsRLSULaUmGR4P/2AhwfNjzu/xuYv8dRiV0ILwdoUdnb8ba81EdG17oq7h
    BZGCumRMJoV9gxQy44Y553+eaM/MTX4kqhPU3rLhvavOYzemwyNE3xZGbOqyzDt/
    inkhVYR1AIuzznd6nA1VJkSX0dOl+F3PVmjBeEXhRUGzgBLaenKJd5n6oUKDDk2J
    Cj5BcvS7sutSWJHeF7c0Vg0qUjFagCvkt+oVhAMx/ivGN5WhVrlDdq62sbhXdHlZ
    wQuk2lsu0QPhQjNcjWVO7DzueaBbUH9vrB3WStDUrxiSFEr0wV10kWbACcc+vBRU
    qzPH3hdiOhLSJPYumg+Zqq48JqORn9KBMWFV3I0ynw6gnBII3w3y22QdoKlDDcmr
    Ih1i6TaAYHndXzoTLUI+M4nXv7q0TFgBhxIhtHkpYUx4P3TyNv+eR28G4+Iug+4X
    SMJx0p2irM+lculGm57J06EEUwatfRtdaYU86xy44Agg2Rp7lwhQyrDXN9jbP2lB
    zvGQEpo7gt1jGDT/o9Jlj0eA2ZciCRHkuRFsY5SArP03jzzD0Q9IqlqFC7IV+3kv
    LEkWjuMLquVc/mHPAVskjgfqdYsri7CpFujofVOYzayZgYVKs2e125ZgibxolDXh
    GFXuCwzl97P43EIbzKCIKJGKOGWnI7NUGes81SKCk94tilkEcDkkZezw4Y6srYVE
    =QKcs
    -----END PGP PUBLIC KEY BLOCK-----
