---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: production
  namespace: capi
  labels:
    ciliumChart: enabled
spec:
  topology:
    variables:
      - name: talosVersion
        value: v1.13.0
      - name: controlPlaneVIP
        value: 10.10.104.11
    classRef:
      name: talos-proxmox-clusterclass-v0.0.1
    version: v1.35.0
    controlPlane:
      replicas: 2
    workers:
      machineDeployments:
        - class: default-worker
          name: default
          replicas: 2
