apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openbao
  namespace: openbao
spec:
  chart:
    spec:
      chart: openbao
      sourceRef:
        kind: HelmRepository
        name: openbao
        namespace: flux-system
      # version:
  interval: 24h
