apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium
  namespace: capi
spec:
  clusterSelector:
    matchLabels:
      ciliumChart: enabled
  repoURL: oci://quay.io/cilium/charts
  chartName: cilium
  version: 1.19.4
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    # install:
    #   createNamespace: true
  valuesTemplate: |
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
        cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
    ipam:
      mode: kubernetes
    cgroup:
      autoMount:
        enabled: false
    cgroup:
      hostRoot: /sys/fs/cgroup
    k8sServiceHost: localhost
    k8sServicePort: 7445
