apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-db
  namespace: litellm
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  storage:
    size: 5Gi
    storageClass: ceph-rbd-pve
