apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 24h
  url: oci://ghcr.io/berriai/litellm-helm
  provider: generic
  secretRef:
    name: ghcr-auth
  ref:
    semver: "1.95.0"
