apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-profilarr-0
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-pve
  resources:
    requests:
      storage: 5G
  volumeName: pvc-b4e6a197-ad03-47cc-9970-425773382dcb
