apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-pve-unreplicated
  resources:
    requests:
      storage: 2T
