apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: istio-system
spec:
  chart:
    spec:
      chart: ztunnel
      sourceRef:
        kind: HelmRepository
        name: istio-release
        namespace: istio-system
      version: "1.30.3"
  interval: 24h
