apiVersion: apps/v1
kind: Deployment
metadata:
  name: routinator
  namespace: default
  labels:
    app: routinator
spec:
  selector:
    matchLabels:
      app: routinator
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: routinator
    spec:
      containers:
        - name: routinator
          image: nlnetlabs/routinator:v0.15.1
          args:
            - "server"
            - "--rtr"
            - "[::]:3323"
            - "--http"
            - "[::]:8323"
          resources:
            # requests:
            #   cpu: 100m
            #   memory: 6G
            limits:
              cpu: 100m
              memory: 6G
          livenessProbe:
            tcpSocket:
              port: 8323
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8323
              name: http
            - containerPort: 3323
              name: rtr
          # volumeMounts:
      # volumes:
      restartPolicy: Always
