{
 "title": "bgp.tools Customer Example Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ASN",
    "query": {
     "query": "label_values(bgptools_asn_upstreams,asn)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Upstreams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bgptools_asn_upstreams{asn=\"$ASN\"}"
    }
   ]
  },
  {
   "title": "Downstreams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bgptools_asn_downstreams{asn=\"$ASN\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bgptools_asn_peers{asn=\"$ASN\"}"
    }
   ]
  },
  {
   "title": "AS Cone",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bgptools_asn_cone{asn=\"$ASN\"}"
    }
   ]
  },
  {
   "title": "Upstreams",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "bgptools_asn_upstream_visible{asn=\"$ASN\"}",
     "legendFormat": "IPv{{family}} - {{upstream}}"
    }
   ]
  },
  {
   "title": "Downstreams",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "bgptools_asn_downstream_visible{asn=\"$ASN\"}",
     "legendFormat": "IPv{{family}} - {{upstream}}"
    }
   ]
  },
  {
   "title": "Peering over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bgptools_asn_peers{asn=\"$ASN\"}",
     "legendFormat": "AS{{asn}}"
    }
   ]
  }
 ]
}