apiVersion: v1
kind: Service
metadata:
  name: poweradmin
  namespace: default
spec:
  selector:
    app: poweradmin
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
