apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: netbox-oci
  namespace: default
spec:
  interval: 10m
  url: oci://ghcr.io/netbox-community/netbox-chart/netbox
  ref:
    semver: "8.0.24"
