apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: TalosControlPlaneTemplate
metadata:
  name: talos-proxmox-clusterclass-v0.0.1
  namespace: capi
spec:
  template:
    spec:
      machineNamingStrategy:
        template: "{{ .talosControlPlane.name }}-{{ .random }}"
      controlPlaneConfig:
        controlplane:
          generateType: controlplane
          strategicPatches:
            - |
              machine:
                install:
                  disk: /dev/sda
            - |
              machine:
                kubelet:
                  extraArgs:
                    cloud-provider: external
                    rotate-server-certificates: "true"
                features:
                  kubernetesTalosAPIAccess:
                    enabled: true
                    allowedRoles:
                      - os:reader
                    allowedKubernetesNamespaces:
                      - kube-system
              cluster:
                externalCloudProvider:
                  enabled: true
                  manifests:
                    - https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml
                    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
                network:
                  cni:
                    name: none
                proxy:
                  disabled: true
