apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-jellyfin
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-pve
  resources:
    requests:
      storage: 30G
