apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mail.as216455.net
  namespace: traefik
spec:
  entryPoints:
    - mail
    - mailsecure
  routes:
    - kind: Rule
      match: Host(`mail.as216455.net`)
      services:
        - kind: Service
          name: stalwart
          namespace: stalwart
          port: mgmt

    - kind: Rule
      match: Host(`web.mail.as216455.net`)
      services:
        - kind: Service
          name: bulwark
          namespace: stalwart
          port: http

  tls:
    secretName: mail.as216455.net-prod-tls
