apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: proxmox-cluster
  namespace: cluster-api
spec:
  schedulerHints:
    memoryAdjustment: 0
  allowedNodes:
  - pve
  controlPlaneEndpoint:
    host: 10.10.104.11
    port: 6443
  dnsServers:
  - 9.9.9.9
  ipv4Config:
    addresses:
    - 10.10.104.100-10.10.104.200
    gateway: 10.10.104.1
    prefix: 24
