apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  storageClassName: ceph-rbd-hdd-pve
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Gi
