apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-config
  namespace: grocy
  labels:
    app: grocy
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
