apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: test-backup
  labels:
    app: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: busybox:latest
          command:
            - sleep
            - "36000"
          volumeMounts:
            - name: volume
              mountPath: "/data"

      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: test-volume
