# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: oxidized-volume
#   namespace: default
#   labels:
#     app: oxidized
# spec:
#   storageClassName: ceph-rbd-pve
#   accessModes:
#     - "ReadWriteOnce"
#   resources:
#     requests:
#       storage: 5G

null
