apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-bridge-signal-db
  namespace: matrix
spec:
  instances: 1
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: false

  # Require 1Gi of space
  storage:
    size: 5Gi
    storageClass: ceph-block

  # plugins:
  #   - name: barman-cloud.cloudnative-pg.io
  #     isWALArchiver: true
  #     parameters:
  #       barmanObjectName: synapse-staging-store
