apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: loki
  namespace: monitoring
spec:
  store: k8s-objectstore-ssd
  displayName: loki
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki
  namespace: monitoring
spec:
  generateBucketName: loki
  storageClassName: ceph-objectstore-ssd-pve
  additionalConfig:
    bucketOwner: "loki"
