apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talos-proxmox-clusterclass-v0.0.1
  namespace: capi
spec:
  template:
    spec:
      generateType: worker
      strategicPatches:
        - |
          machine:
            install:
              disk: /dev/sda
            kubelet:
              extraArgs:
                cloud-provider: external
          cluster:
            network:
              cni:
                name: none
            proxy:
              disabled: true
