apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
  namespace: firefly
spec:
  chart:
    spec:
      chart: firefly-iii
      sourceRef:
        kind: HelmRepository
        name: firefly
        namespace: flux-system
      version: "1.10.1"
  interval: 24h
  values:
    replicaCount: 1
    deploymentStrategyType: RollingUpdate

    persistence:
      enabled: true
      storageClassName: "ceph-fs-ssd-pve"
      accessModes: ReadWriteOnce
      storage: 5Gi

    # -- Environment variables for Firefly III. See docs at: https://github.com/firefly-iii/firefly-iii/blob/main/.env.example
    config:
      # -- Set this to the name of a secret to load environment variables from. If defined, values in the secret will override values in config.env
      existingSecret: "firefly-env"

      # -- Set environment variables from configMaps or Secrets
      envValueFrom: {}

      # -- Directly defined environment variables. Use this for non-secret configuration values.
      env:
        DB_HOST: firefly-postgres-rw
        DB_CONNECTION: pgsql
        DB_PORT: "5432"
        DB_DATABASE: app
        DB_USERNAME: app
        DEFAULT_LANGUAGE: "en_US"
        DEFAULT_LOCALE: "equal"
        TZ: "Europe/Amsterdam"
        TRUSTED_PROXIES: "**"
        APP_URL: "https://firefly.i.as216455.net"

    # -- A cronjob for [recurring Firefly III tasks](https://docs.firefly-iii.org/firefly-iii/advanced-installation/cron/).
    cronjob:
      # -- Set to true to enable the CronJob. Note that you need to specify either cronjob.auth.existingSecret or cronjob.auth.token for it to actually be deployed.
      enabled: false

      # -- Authorization for the CronJob. See https://docs.firefly-iii.org/firefly-iii/advanced-installation/cron/#request-a-page-over-the-web
      auth:
        # -- The name of a secret containing a data.token field with the cronjob token
        existingSecret: ""

        # -- The name of the key in the existing secret to get the cronjob token from
        secretKey: "token"

        # -- The token in plain text
        token: ""

      # -- Annotations for the CronJob
      annotations: {}

      # -- When to run the CronJob. Defaults to 03:00 as this is when Firefly III executes regular tasks.
      schedule: "0 3 * * *"

      # -- How many pods to keep around for successful jobs
      successfulJobsHistoryLimit: 3

      # -- How many pods to keep around for failed jobs
      failedJobsHistoryLimit: 1

      # -- How to treat failed jobs
      restartPolicy: OnFailure

    httpRoute:
      enabled: false
      annotations: {}
      hostnames: []
      parentRefs: []
      filters: []
      additionalRules: []

    resources:
      limits:
        cpu: 2000m
        memory: 2G
      requests:
        cpu: 1000m
        memory: 512Mi
