function import_customer_inet6_pref(int local_pref) {
  import_default_inet6(local_pref);

  reject;
}

function import_customer_inet4_pref(int local_pref) {
  import_default_inet4(local_pref);

  reject;
}
