apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-koen
  namespace: default
  labels:
    app: actual-budget-koen
spec:
  storageClassName: ceph-rbd-pve
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
