apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio-release
        namespace: istio-system
      version: "1.30.3"
  interval: 24h
  values:
    profile: ambient
