apiVersion: apps/v1
kind: Deployment
metadata:
  name: stalwart
  namespace: stalwart
  labels:
    app: stalwart
spec:
  replicas: 1
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: stalwart
  template:
    metadata:
      labels:
        app: stalwart
    spec:
      initContainers:
        - name: bootstrap
          image: alpine
          command:
            - rm
            - /opt/stalwart/data/LOCK
          volumeMounts:
            - name: data
              mountPath: /opt/stalwart/data
      containers:
        - name: stalwart
          image: stalwartlabs/stalwart:v0.15.4-alpine
          imagePullPolicy: IfNotPresent
          # command:
          #   - sleep
          #   - "3600"
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
            - containerPort: 443
            - containerPort: 25
            - containerPort: 587
            - containerPort: 465
            - containerPort: 143
            - containerPort: 993
            - containerPort: 4190
          volumeMounts:
            - name: config
              mountPath: /opt/stalwart/etc
            - name: data
              mountPath: /opt/stalwart/data
            - name: mail-as216455-net-cert
              mountPath: /cert/mail.as216455.net
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: stalwart-config
        - name: data
          persistentVolumeClaim:
            claimName: stalwart-data
        - name: mail-as216455-net-cert
          secret:
            secretName: mail.as216455.net-prod-tls
