# apiVersion: traefik.io/v1alpha1
# kind: IngressRouteTCP
# metadata:
#   name: imap-ingress
#   namespace: traefik
# spec:
#   entryPoints:
#     - imap
#   tls:
#     secretName: as216455.net-prod-tls
#   routes:
#     - match: HostSNI(`*`)
#       services:
#         - name: stalwart
#           namespace: stalwart
#           port: imap
#           proxyProtocol:
#             version: 2
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: imaps-ingress
  namespace: traefik
spec:
  entryPoints:
    - imaps
  tls:
    passthrough: true
  routes:
    - match: HostSNI(`*`)
      services:
        - name: stalwart
          namespace: stalwart
          port: imaps
          proxyProtocol:
            version: 2
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: smtp-ingress
  namespace: traefik
spec:
  entryPoints:
    - smtp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: stalwart
          namespace: stalwart
          port: smtp
          proxyProtocol:
            version: 2
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: submission-ingress
  namespace: traefik
spec:
  entryPoints:
    - submission
  tls:
    passthrough: true
  routes:
    - match: HostSNI(`*`)
      services:
        - name: stalwart
          namespace: stalwart
          port: submission
          proxyProtocol:
            version: 2
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: submissions-ingress
  namespace: traefik
spec:
  entryPoints:
    - submissions
  tls:
    passthrough: true
  routes:
    - match: HostSNI(`*`)
      services:
        - name: stalwart
          namespace: stalwart
          port: submissions
          proxyProtocol:
            version: 2
