apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-lucas
  namespace: default
  labels:
    app: actual-budget-lucas
spec:
  storageClassName: ceph-rbd-pve
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
