apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: matrixrtc-muxedudp-ingress
  namespace: traefik
spec:
  entryPoints:
    - matrixrtc-muxedudp
  routes:
    - services:
        - name: matrix-stack-matrix-rtc-sfu-muxed-udp
          namespace: matrix
          port: 30002
