apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio-release
        namespace: istio-system
      version: "1.30.4"
  interval: 24h
  values:
    profile: ambient
