apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: doubleblind.nl
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`doubleblind.nl`)
      services:
        - kind: Service
          name: doubleblind-site
          namespace: default
          port: http

  tls:
    secretName: doubleblind.nl-prod-tls
