apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sabnzbd
  namespace: media
spec:
  selector:
    matchLabels:
      app: sabnzbd # has to match .spec.template.metadata.labels
  replicas: 1
  template:
    metadata:
      labels:
        app: sabnzbd # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          resources:
            requests:
              cpu: 1000m
              memory: 1G
            limits:
              cpu: 2000m
              memory: 2G
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /config
            - name: library
              mountPath: /library
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-sabnzbd
        - name: library
          persistentVolumeClaim:
            claimName: library
      restartPolicy: Always
