apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sabnzbd
  namespace: media
spec:
  selector:
    matchLabels:
      app: sabnzbd
  replicas: 1
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:5.1.0
          resources:
            requests:
              cpu: 1000m
              memory: 2000Mi
            limits:
              cpu: 2000m
              memory: 2000Mi
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /config
            - name: library
              mountPath: /library
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-sabnzbd
        - name: library
          persistentVolumeClaim:
            claimName: library
      restartPolicy: Always
