apiVersion: v1
kind: Service
metadata:
  name: stalwart
  namespace: stalwart
  labels:
    app: stalwart
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: smtps
      port: 465
      targetPort: 465
    - name: submission
      port: 587
      targetPort: 587
    - name: imap
      port: 143
      targetPort: 143
    - name: imaps
      port: 993
      targetPort: 993
    - name: pop3
      port: 110
      targetPort: 110
    - name: pop3s
      port: 995
      targetPort: 995
    - name: sieve
      port: 4190
      targetPort: 4190
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: mgmt
      port: 8080
      targetPort: 8080

  selector:
    app: stalwart
