kind: ConfigMap
apiVersion: v1
metadata:
  name: doubleblind-data
  namespace: default
data:
  index.html: |
    <html>
      <body style="font-family:monospace">
        <p>doubeblind</p>
      </body>
    </html>
