apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: talos
  namespace: capi-talos-control-plane-system
spec:
  version: v0.6.0-alpha.1
  fetchConfig:
    url: https://github.com/stingalleman/cluster-api-control-plane-provider-talos/releases/download/v0.6.0-alpha.1/control-plane-components.yaml
